version: '3'

services:
  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
    ports:
      - "5000:5000"
    volumes:
      - ./back-end:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=apple
      - DB_PORT=3306
    command: nodemon server.js
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"  # tránh xung đột cổng với máy host
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "apple"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
 