version: '3.8'

services:
  backend:
    build: ./back-end
    container_name: backend
    restart: always
    volumes:
      - ./back-end:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: apple
      DB_PORT: 3306
      PORT: 5000
      JWT_SECRET: TONY_NGUYEN
      EMAIL_USER: nguyenlehoangtu120405@gmail.com
      EMAIL_PASS: 0777527125
      FRONTEND_URL: http://localhost:3000
    command: nodemon --legacy-watch server.js

  frontend:
    build: ./front-end
    container_name: frontend
    restart: always
    volumes:
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    command: npm run dev
    depends_on:
      - backend

